/*
 * BoundarySweepFixtureTest.java
 * Copyright (C) 2026 Chris Burdess
 *
 * This file is part of Gonzalez, a streaming XML parser.
 * For more information please visit https://www.nongnu.org/gonzalez/
 *
 * Gonzalez is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Gonzalez is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Gonzalez.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.bluezoo.gonzalez;

import org.junit.Test;

/**
 * Applies {@link ChunkFuzzer} to the boundary-sweep fixtures generated by
 * {@link BoundarySweepFixtureGenerator}, establishing that today's legacy
 * tokenizer correctly handles a 2/3/4-byte UTF-8 sequence straddling a chunk
 * boundary inside an element name, an attribute name, an attribute value,
 * text content, a comment, a CDATA section, and processing instruction data.
 * <p>
 * This baseline is reused from milestone M2 onward to diff the legacy
 * tokenizer against the byte-native tokenizer on the same fixtures.
 *
 * @author <a href='mailto:dog@gnu.org'>Chris Burdess</a>
 */
public class BoundarySweepFixtureTest {

    @Test
    public void testTwoByteCharBoundarySweep() {
        byte[] data = BoundarySweepFixtureGenerator.generate(BoundarySweepFixtureGenerator.TWO_BYTE_CHAR);
        ChunkFuzzer.assertChunkInvariant("two-byte boundary sweep", data);
    }

    @Test
    public void testThreeByteCharBoundarySweep() {
        byte[] data = BoundarySweepFixtureGenerator.generate(BoundarySweepFixtureGenerator.THREE_BYTE_CHAR);
        ChunkFuzzer.assertChunkInvariant("three-byte boundary sweep", data);
    }

    @Test
    public void testFourByteCharBoundarySweep() {
        byte[] data = BoundarySweepFixtureGenerator.generate(BoundarySweepFixtureGenerator.FOUR_BYTE_CHAR);
        ChunkFuzzer.assertChunkInvariant("four-byte boundary sweep", data);
    }

}
